version: "3.7"

services:
  server:
    image: dccn/qaas-server
    container_name: qaas_server_container
    build:
      context: .
      dockerfile: Dockerfile-server
    env_file:
      - ./configs/qaas-database.env
    ports:
      - 5111:5111
    volumes:
      - ./data:/data
    networks:
      - qaasnet
    depends_on:
      - db
  db:
    image: postgres:11
    env_file:
      - ./configs/qaas-database.env
    volumes:
      - ./init/01-initialize-database.sh:/docker-entrypoint-initdb.d/01-initialize-database.sh:ro
    networks:
      - qaasnet
    restart: always

networks:
  qaasnet:

volumes:
  postgres: